### ISSUE TITLE
NPE SmoochService

### ISSUE THREAD

**Issue by roxrook** [zendesk/sunshine-conversations-android#110]
Hi there, 

I'm seeing this crash quite often on Fabric:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.smooch.core.service.SmoochService.b(java.lang.String, io.smooch.core.SmoochCallback)' on a null object reference
       at io.smooch.core.b.a(Unknown Source)
       at io.smooch.core.b.b(Unknown Source)
       at io.smooch.core.b.a(Unknown Source)
       at io.smooch.core.Conversation.uploadImage(Unknown Source)
       at io.smooch.ui.fragment.ConversationFragment.uploadImage(Unknown Source)
       at io.smooch.ui.fragment.ConversationFragment.uploadImage(Unknown Source)
       at io.smooch.ui.fragment.ConversationFragment.access$2200(Unknown Source)
       at io.smooch.ui.fragment.ConversationFragment$9.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
Any idea what could go wrong? Thanks!

- So far this crashes happened only on Android 7.
- I'm using the latest SDK which is `5.7.3`

**Comment by wmora** [comment]
Thanks for reporting, unfortunately I was not able to reproduce the issue. How are your users using Smooch? Are new users uploading an image as the first message? Are your users authenticated or not? It would be very helpful if you know how to reproduce the crash

**Comment by wmora** [comment]
Closing due to inactivity
