### ISSUE TITLE
NPE on Android 8

### ISSUE THREAD

**Issue by islamassi** [zendesk/sunshine-conversations-android#124]
**Bug Report [crash]**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.smooch.core.service.SmoochService.a(java.lang.String, java.lang.String, io.smooch.core.SmoochCallback, boolean)' on a null object reference
       at io.smooch.core.c$3$1.run(Unknown Source:38)
       at io.smooch.core.service.SmoochService.U(Unknown Source:19)
       at io.smooch.core.service.SmoochService.a(Unknown Source:69)
       at io.smooch.core.service.SmoochService.a(Unknown Source)
       at io.smooch.core.service.SmoochService$12.run(Unknown Source:10)
       at io.smooch.core.service.SmoochService$8$1.a(Unknown Source:194)
       at io.smooch.core.service.SmoochService$8$1.a(Unknown Source:2)
       at io.smooch.core.b.f$15.a(Unknown Source:27)
       at io.smooch.core.b.a.b$1$2.run(Unknown Source:16)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

- SDK version: 5.13.2
- OS version:   8

Crash details on Fabric:
http://crashes.to/s/153825319e1

**Comment by islamassi** [comment]
The issue still persists in version `5.14.1`
Fabric: [http://crashes.to/s/153825319e1](url)

**Comment by DataWearsAHood** [comment]
Hello!

Looks like a few nullpointer crashes have been fixed since this issue was first reported (v5.15.0 v7.0.2).
Please reopen this issue if you are still experiencing this crash with the latest release.
