### ISSUE TITLE
Crashes caused by ConcurrentModificationException

### ISSUE THREAD

**Issue by maxoumime** [zendesk/sunshine-conversations-android#127]
Hi all, I am receiving crash reports when users are opening ConversationActivity. Looks like a dup of @islamassi 's issue #117 but this issue is closed.

I couldn't find a specific pattern, it looks like it randomly happens when opening ConversationActivity. I received crash reports coming from multiple devices and OS versions.

 **Please tell us about your environment:**
- SDK version: 5.14.5
- OS version: Android 8 and 9

Stack trace:
```
Caused by java.util.ConcurrentModificationException
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
       at java.util.LinkedList$ListItr.next(LinkedList.java:888)
       at io.smooch.core.c.y(Unknown Source:26)
       at io.smooch.core.c.a(Unknown Source:9)
       at io.smooch.core.c.m(Unknown Source:5)
       at io.smooch.core.Conversation.markAllAsRead(Unknown Source:68)
       at io.smooch.ui.fragment.ConversationFragment.onResume(Unknown Source:96)
```

**Comment by sergeyfitis** [comment]
I have the same issue too. SDK version: 5.14.5. Will try to update too 5.15.5 and hope it fixes the issue.

**Comment by wmora** [comment]
@sergeyfitis are you able to reproduce by any chance? If so, could you provide the steps to reproduce?

**Comment by islamassi** [comment]
http://crashes.to/s/cefb7d63c71

* SDK version: 5.14.2
* OS version: Android 8 (95%) and 9 (5%)

**Comment by wmora** [comment]
Closing due to inactivity
