### ISSUE TITLE
Smooch SDK leaks Closeable

### ISSUE THREAD

**Issue by prfarlow1** [zendesk/sunshine-conversations-android#145]
With a StrictMode policy that kills the app on a leaked Closeable as suggested here https://developer.android.com/reference/android/os/StrictMode, I get this stack trace:

```
2020-07-13 22:52:52.647 com.myapp D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.io.FileInputStream.finalize(FileInputStream.java:493)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.io.FileInputStream.<init>(FileInputStream.java:174)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.smooch.core.c.b.b(Unknown Source:2)
        at io.smooch.core.c.d.a(Unknown Source:11)
        at io.smooch.core.c.o.a(Unknown Source:24)
        at io.smooch.core.c.h.c(Unknown Source:12)
        at io.smooch.core.service.SmoochService.a(Unknown Source:80)
        at io.smooch.core.e.onServiceConnected(Unknown Source:54)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-13 22:52:52.647 com.myapp W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

This occurs after Smooch.init is called (and a success callback is received) in my application's onCreate. Smooch Android SDK 7.0.1. Device was a Pixel 2 XL on Android 10

**Comment by wmora** [comment]
Thanks for the report, I'll file it internally for the team to review

**Comment by DataWearsAHood** [comment]
Hi Peter,

Thanks for reporting this bug; I've added it to the fix pipeline!
Subscribe to [this repo's releases page](https://github.com/zendesk/sunshine-conversations-android/releases) to know once it's been fixed!
