### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'io.smooch.core.model.ConversationDto io.smooch.core.service.SmoochService.r()' on a null object reference

### ISSUE THREAD

**Issue by Pakornz** [zendesk/sunshine-conversations-android#159]
Bug Report

App crashes with the following exception:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'io.smooch.core.model.ConversationDto io.smooch.core.service.SmoochService.r()' on a null object reference
       at io.smooch.core.e$h$a$a.run(:30)
       at io.smooch.core.service.SmoochService$ai$a.a(:298)
       at io.smooch.core.service.SmoochService$ai$a.a(:2)
       at dxn.onResponse(:52)
       at esj$a$1$1.run(:41)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8258)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

environment:
- SDK version Android (smooch 8.2.0)
- OS version : Android 11 on device Oppo reno 5

**Comment by DataWearsAHood** [comment]
Hello @Pakornz,
Are you able to reproduce this issue using the /Demo app? or with a minimal code example?
What are the [repeatable] steps to reproduce the crash?
Can you reproduce the crash 100% of the time?
