### ISSUE TITLE
Android Smooch SDK - LocationServices.API is not available on this device. Connection

### ISSUE THREAD

**Issue by aneesahamed1995** [zendesk/sunshine-conversations-android#162]
Android Smooch SDK Crashes the app for Huawei devices. Please find the stackTrace below. 

is Smooch SDk Available for Huawei? Because upon checking Smooch SDK Source code. SDK trying to get Location from Google Service Fused Location API. what about Google service not available device?

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: com.google.android.gms.common.api.ApiException: 17: API: LocationServices.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
       at com.google.android.gms.tasks.zzw.getResult(zzw.java:3)
       at io.smooch.ui.fragment.ConversationFragment$15.onComplete(ConversationFragment.java)
       at com.google.android.gms.tasks.zzi.run(zzi.java:1)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by aneesahamed1995** [comment]
Team, Any update on this issue?

**Comment by aneesahamed1995** [comment]
@DataWearsAHood  
I have given device details as a screenshot, Class Details for root cause and Full StackTrace.
We cant able to reproduce the issue. but since we check the SDK source code. this is direct case if code reach that statement. Kindly Please check.

**Comment by DataWearsAHood** [comment]
Hi @aneesahamed1995 

The bug has been filed with the team. Keep an eye on future release notes for a mention of this bug/fix.
