### ISSUE TITLE
App crash when i click `Share Localtion`

### ISSUE THREAD

**Issue by xukai59740** [zendesk/sunshine-conversations-android#172]
App crash when i click `Share Localtion`

 **I'm submitting a ...**
  - [ x ] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

 **What is the current behavior?**
App crash when i click `Share Localtion`

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gms.persistent, PID: 9772
    java.lang.RuntimeException: Unable to instantiate application co.g.App: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1230)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6511)
        at android.app.ActivityThread.access$1400(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1359)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2279)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2267)
        at bhlj.k(:com.google.android.gms@212418037@21.24.18 (120400-383468479):2)
        at bhlj.g(:com.google.android.gms@212418037@21.24.18 (120400-383468479):2)
        at uzd.attachBaseContext(:com.google.android.gms@212418037@21.24.18 (120400-383468479):18)
        at android.app.Application.attach(Application.java:376)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1222)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6511) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:220) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7520) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.content.ContentService.registerContentObserver(ContentService.java:344)
        at android.content.IContentService$Stub.onTransact(IContentService.java:524)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

 **What is the expected behavior?**
Toast a message "Location service unavailable， instead of crash

 **Please tell us about your environment:**
- SDK version: 9.0.2
- OS version: 10
- Device: xiaomi 8
- Country: China
- Service: Not install google service and GMS service

**Comment by DataWearsAHood** [comment]
@xukai59740 Is this crash still present with the [latest release](https://github.com/zendesk/sunshine-conversations-android/releases/tag/9.1.1)?
