### ISSUE TITLE
Crash NullPointerException Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference

### ISSUE THREAD

**Issue by ha-yi** [zendesk/sunshine-conversations-android#178]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [x] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

 **What is the current behavior?**
 
We capture some crash on sentry which shown an exception with following stack trace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
    at io.smooch.ui.fragment.ConversationFragment.setServerBanner
    at io.smooch.ui.fragment.ConversationFragment.updateConnectionState
    at io.smooch.ui.fragment.ConversationFragment.onSmoochConnectionStatusChanged
    at io.smooch.ui.ConversationActivity.onSmoochConnectionStatusChanged
    at io.smooch.core.f.onSmoochConnectionStatusChanged
    at io.smooch.core.service.SmoochService$w0.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8414)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

most probably triggered on the following lines, which on this part it didn't have any checking whether the Fragment is attached or not.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/966816/218950639-c9139410-7249-4fa3-a969-18b2fccec97e.png">

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project
Unknown, captured on sentry, and it happened quite a lot.  

 **What is the expected behavior?**
not crashed.

 **Please tell us about your environment:**
- SDK version
   - io.smooch.core:9.1.1
   - io.smooch.ui:9.1.1
 
- OS version: Android 12, 13

 **Other information** 
 please see above images for more detail.

 Thanks.

**Comment by ha-yi** [comment]
any update on this?
