### ISSUE TITLE
AssertionError: impossible, caused by NoSuchMethodException

### ISSUE THREAD

**Issue by justincpollard** [zendesk/sunshine-conversations-android#93]
This isn't a major crash, but I've seen 6 `AssertionError: impossible` caused by `NoSuchMethodException` crashes in my production app. Potentially an issue with Smooch's version/usage of Gson given the below stacktrace:

```
Fatal Exception: java.lang.AssertionError: impossible
       at java.lang.Enum$1.create(Enum.java:45)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Class.getEnumConstants(Class.java:1072)
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:778)
       at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:817)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.Gson.fromJson(Gson.java:886)
       at com.google.gson.Gson.fromJson(Gson.java:852)
       at com.google.gson.Gson.fromJson(Gson.java:801)
       at com.google.gson.Gson.fromJson(Gson.java:773)
       at io.smooch.core.b.a.c.a(Unknown Source)
       at io.smooch.core.b.c.c(Unknown Source)
       at io.smooch.core.service.SmoochService.a(Unknown Source)
       at io.smooch.core.b.a(Unknown Source)
       at io.smooch.core.b$1.onServiceConnected(Unknown Source)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1273)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1290)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6117)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.NoSuchMethodException: values []
       at java.lang.Class.getDeclaredMethod(Class.java:635)
       at java.lang.Enum$1.create(Enum.java:41)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Class.getEnumConstants(Class.java:1072)
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:778)
       at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:817)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.Gson.fromJson(Gson.java:886)
       at com.google.gson.Gson.fromJson(Gson.java:852)
       at com.google.gson.Gson.fromJson(Gson.java:801)
       at com.google.gson.Gson.fromJson(Gson.java:773)
       at io.smooch.core.b.a.c.a(Unknown Source)
       at io.smooch.core.b.c.c(Unknown Source)
       at io.smooch.core.service.SmoochService.a(Unknown Source)
       at io.smooch.core.b.a(Unknown Source)
       at io.smooch.core.b$1.onServiceConnected(Unknown Source)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1273)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1290)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6117)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by wmora** [comment]
Thanks! Which version of the SDK are you using?

**Comment by justincpollard** [comment]
Aw, sorry, should have specified: 4.8.1

**Comment by mholzel** [comment]
FYI, this seems to be somehow related to either the version of Android Studio, or the gradle plugin. I have seen such errors for other projects when upgrading from Android Studio 2.XX to Android Studio 3.XX

**Comment by Jawnnypoo** [comment]
Are you using ProGuard @justincpollard ? I think this is a proguard related issue. See here: 
https://stackoverflow.com/questions/20651575/android-release-apk-crash-with-java-lang-assertionerror-impossible-in-java-lang

**Comment by justincpollard** [comment]
@Jawnnypoo thanks for the reply! I am using proguard. Looking at that link, though, it appears the suggested solution is to include the default android proguard config file using:

`proguardFile getDefaultProguardFile('proguard-android.txt')`

In addition to my own `proguard.cfg` I'm also using the default proguard config using the suggested method, so the issue seems to be caused by something else.

**Comment by Raghav29Sharma** [comment]
# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

Add this into your proguard properties file.
