### ISSUE TITLE
NullPointer from a toString() in SmoochService

### ISSUE THREAD

**Issue by Scythe14** [zendesk/sunshine-conversations-android#99]
Hi guys, just had that stacktrace from one of my apps. Can you look up what is causing it and fix it please ? 

Thank you

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at java.text.Normalizer.normalize(Normalizer.java:170)
       at io.smooch.core.b.a.b.a(Unknown Source)
       at io.smooch.core.b.a.b.a(Unknown Source)
       at io.smooch.core.b.a.b.a(Unknown Source)
       at io.smooch.core.b.a.a(Unknown Source)
       at io.smooch.core.b.f.b(Unknown Source)
       at io.smooch.core.service.SmoochService$6.run(Unknown Source)
       at io.smooch.core.service.SmoochService.c(Unknown Source)
       at io.smooch.core.service.SmoochService.G(Unknown Source)
       at io.smooch.core.service.SmoochService.C(Unknown Source)
       at io.smooch.core.service.SmoochService.B(Unknown Source)
       at io.smooch.core.service.SmoochService.n(Unknown Source)
       at io.smooch.core.service.SmoochService$3.a(Unknown Source)
       at io.smooch.core.service.SmoochService$3.a(Unknown Source)
       at io.smooch.core.b.f$9.a(Unknown Source)
       at io.smooch.core.b.a.b$1$2.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by jugarrit** [comment]
Might you happen to know what was going on in your application before the crash occurred? What kind of interaction with Smooch caused this? Message send, update, etc?

**Comment by wmora** [comment]
Closing due to inactivity
